//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skaf.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("skaf.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table style=&quot;width:545.75pt&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;padding:0cm;width:102pt&quot;&gt;
        ///                &lt;p style=&quot;line-height:105%;margin:0cm;font-family:Calibri,sans-serif;font-size:11pt&quot;&gt;
        ///                    &lt;span style=&quot;font-family:&amp;quot;Times New Roman&amp;quot;,serif;font-size:10pt;line-height:105%&quot;&gt;@FOTO&lt;/span&gt;
        ///                &lt;/p&gt;
        ///            &lt;/td&gt;
        ///            &lt;td style=&quot;padding:0cm;width:443.75pt&quot;&gt;
        ///                &lt;p style=&quot;margin:0cm;font-family:Calibri,sans-serif;font-size:11 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string assinatura {
            get {
                return ResourceManager.GetString("assinatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit1 {
            get {
                object obj = ResourceManager.GetObject("edit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eng {
            get {
                object obj = ResourceManager.GetObject("eng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Formulário_Designação_de_Beneficiários {
            get {
                object obj = ResourceManager.GetObject("Formulário_Designação_de_Beneficiários", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    SKA em parceria com a GYMPASS, vem para proporcionar
        ///    e facilitar o seu acesso em academias.
        ///    &lt;br /&gt; &lt;b&gt;Nosso propósito é ajudar nossos colaboradores a ter uma vida mais ativa!&lt;/b&gt;
        ///&lt;/p&gt;
        ///&lt;h5&gt;Sobre o Gympass:&lt;/h5&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Mensalidades com até 75% de desconto dos preços aplicados em mercado.&lt;/li&gt;
        ///    &lt;li&gt;Possui 9 opções de planos.&lt;/li&gt;
        ///    &lt;li&gt;É permitido um check-in por dia.&lt;/li&gt;
        ///    &lt;li&gt;A mensalidade do titular é descontada em dolha de pagamento.&lt;/li&gt;
        ///    &lt;li&gt;Pod [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Gympass {
            get {
                return ResourceManager.GetString("Gympass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Lista_de_procedimentos___Odonto {
            get {
                object obj = ResourceManager.GetObject("Lista_de_procedimentos___Odonto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_SKA_Azul {
            get {
                object obj = ResourceManager.GetObject("Logo_SKA_Azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Microsoft_logo {
            get {
                object obj = ResourceManager.GetObject("Microsoft_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] planilha_para_inclusões__TIPAN {
            get {
                object obj = ResourceManager.GetObject("planilha_para_inclusões__TIPAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    A SKA oferece um Plano Odontológico à todos os colaboradores com a possibilidade de inclusão de
        ///    familiares (irmãos, pais, mães e filhos), porém o custo é de responsabilidade de cada colaborador que optar (a SKA não pagará 50% como no plano de saúde).
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Caso você deseje incluir familiares ao benefício, lembre-se, todos do grupo familiar deverão utilizar do mesmo plano.
        ///    &lt;br /&gt;Temos a o~pção de dois tipos de plano:&lt;br /&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;&lt;b&gt;Plano Gold&lt;/b&gt;  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string PlanoOdonto {
            get {
                return ResourceManager.GetString("PlanoOdonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    Abaixo e em anexo, algumas informações sobre o nosso plano de saúde.
        ///    Me avise se optar ou não pelo plano para que eu possa fazer sua inclusão junto a UNIMED. Favor responder neste e-mail mesmo!
        ///&lt;/p&gt;
        ///&lt;h5&gt;Alguns detalhes do plano:&lt;/h5&gt;
        ///&lt;ol&gt;
        ///    &lt;li&gt;O plano Unimed pela SKA é sem co-participação, ou seja, você não será cobrado de consultas ou exames realizados.&lt;/li&gt;
        ///    &lt;li&gt;O plano é Semi-Privativo Hospitalar.&lt;/li&gt;
        ///    &lt;li&gt;O valor do plano é de R$465,55, sendo que a SKA paga  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string PlanoUnimed {
            get {
                return ResourceManager.GetString("PlanoUnimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    A SKA fornece um seguro de vida a todos os colaboradores, a adesão ao seguro é obrigatória.
        ///    Há um desconto simbólico no valor de R$3,00 por mês.&lt;br /&gt;
        ///    Segue em anexo o formulário para preenchimento, assim que preenchido me enviar por e-mail escaneado e o original entregar no ADM
        ///&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;&lt;font color=&quot;red&quot;&gt;Preencher em Estipulante:&lt;/font&gt;SKA Desenvolvimento e Licenciamento de Sistemas LTDA&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Não precisa preencher Subestipulante e Nº de Subcontrato!&lt;/p&gt;
        ///.
        /// </summary>
        internal static string SegudoDeVidaSis {
            get {
                return ResourceManager.GetString("SegudoDeVidaSis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    A SKA fornece um seguro de vida a todos os colaboradores, a adesão ao seguro é obrigatória.
        ///    Há um desconto simbólico no valor de R$3,00 por mês.&lt;br /&gt;
        ///    Segue em anexo o formulário para preenchimento, assim que preenchido me enviar por e-mail escaneado e o original entregar no ADM
        ///&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;&lt;font color=&quot;red&quot;&gt;Preencher em Estipulante:&lt;/font&gt;SKA Desenvolvimento e Licenciamento de Sistemas LTDA&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Não precisa preencher Subestipulante e Nº de Subcontrato!&lt;/p&gt;
        ///.
        /// </summary>
        internal static string SegudoDeVidaSis1 {
            get {
                return ResourceManager.GetString("SegudoDeVidaSis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///    Olá,&lt;br /&gt;
        ///    A SKA fornece um seguro de vida a todos os colaboradores, a adesão ao seguro é obrigatória.
        ///    Há um desconto simbólico no valor de R$3,00 por mês.&lt;br /&gt;
        ///    Segue em anexo o formulário para preenchimento, assim que preenchido me enviar por e-mail escaneado e o original entregar no ADM
        ///&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;&lt;font color=&quot;red&quot;&gt;Preencher em Estipulante:&lt;/font&gt; SKA Automação de Engenharias LTDA&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Não precisa preencher Subestipulante e Nº de Subcontrato!&lt;/p&gt;
        ///.
        /// </summary>
        internal static string SeguroDeVidaAUT {
            get {
                return ResourceManager.GetString("SeguroDeVidaAUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Termo_de_Opção___Dental_SKA {
            get {
                object obj = ResourceManager.GetObject("Termo_de_Opção___Dental_SKA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;head&gt;
        ///    &lt;style&gt;
        ///        body{
        ///            
        ///            font-size:small;
        ///        }
        ///        #meio {
        ///            text-align: center
        ///        }
        ///
        ///        #tabT {
        ///            border-collapse: collapse;
        ///            text-align: center;
        ///            width: 100%;
        ///            font-family: Arial, Helvetica, sans-serif;
        ///            font-size: small;
        ///        }
        ///
        ///            #tabT td {
        ///                padding-top: 5px;
        ///                font-weight: bold;
        ///                padding-right: 40px;
        ///           [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Uniformes {
            get {
                return ResourceManager.GetString("Uniformes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Unimed_Fesp_Nacional___Apresentação {
            get {
                object obj = ResourceManager.GetObject("Unimed_Fesp_Nacional___Apresentação", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///Olá,&lt;br/&gt;
        ///
        ///Você utilizará vale transporte?&lt;br/&gt;
        ///
        ///Se sim, favor me passar as informações a baixo:&lt;/br&gt;
        ///
        ///- Qual a linha de ônibus que utiliza?&lt;/br&gt;
        ///- Qual a empresa que administra a linha?&lt;/br&gt;
        ///- Já possui cartão de transporte? Qual a numeração? &lt;/br&gt;
        ///- Quantas passagens utiliza por dia?&lt;/br&gt;
        ///- Qual o valor unitário da passagem que você utiliza?&lt;/br&gt;
        ///
        ///&lt;/p&gt;
        ///.
        /// </summary>
        internal static string VALE_TRANSPORTE {
            get {
                return ResourceManager.GetString("VALE_TRANSPORTE", resourceCulture);
            }
        }
    }
}
